import {
  ClientId,
  MaliciousIPListEnum,
  IPReputationRiskLevelEnum,
  ClientTypeEnum,
} from './model';

export const defaultMaliciousIPList: MaliciousIPListEnum[] = [
  MaliciousIPListEnum.AnonymousProxyIPs,
  MaliciousIPListEnum.TorIPs,
];

export const defaultIpReputationRiskLevels: IPReputationRiskLevelEnum[] = [
  IPReputationRiskLevelEnum.Low,
  IPReputationRiskLevelEnum.Medium,
  IPReputationRiskLevelEnum.High,
];

export const defaultClientTypes: ClientTypeEnum[] = [
  ClientTypeEnum.DDoSBot,
  ClientTypeEnum.Worm,
  ClientTypeEnum.MaskingProxy,
  ClientTypeEnum.ClickBot,
  ClientTypeEnum.CommentSpamBot,
  ClientTypeEnum.SpamBot,
  ClientTypeEnum.VulnerabilityScanner,
  ClientTypeEnum.HackingTool,
  ClientTypeEnum.Unknown,
];

export const defaultClientIds: ClientId[] = [
  { id: 1, name: 'Firefox' },
  { id: 2, name: 'Internet Explorer' },
  { id: 3, name: 'Chrome' },
  { id: 4, name: 'Safari' },
  { id: 5, name: 'General Crawler' },
  { id: 6, name: 'Googlebot' },
  { id: 7, name: 'Bot' },
  { id: 8, name: 'Opera' },
  { id: 9, name: 'Camino' },
  { id: 10, name: 'Wget' },
  { id: 11, name: 'Maxthon' },
  { id: 12, name: 'Google Translate' },
  { id: 13, name: 'Skipfish' },
  { id: 14, name: 'Google Services' },
  { id: 15, name: 'Verisign ips-agent' },
  { id: 16, name: 'Baidu Spider' },
  { id: 17, name: 'SiteUptime' },
  { id: 18, name: 'Guardster' },
  { id: 19, name: 'Yahoo! Slurp' },
  { id: 20, name: 'NimbuBot' },
  { id: 21, name: 'Nikto' },
  { id: 22, name: 'Are My Sites Up?' },
  { id: 23, name: 'mon.itor.us' },
  { id: 24, name: 'Load Impact' },
  { id: 25, name: 'Host Tracker' },
  { id: 26, name: 'Konqueror' },
  { id: 27, name: 'SurveyBot' },
  { id: 28, name: 'Facebook External Hit' },
  { id: 29, name: 'Google AppEngine' },
  { id: 30, name: 'PycURL' },
  { id: 31, name: 'Twingly Recon' },
  { id: 32, name: 'Twitter Bot' },
  { id: 33, name: 'DataSift Bot' },
  { id: 34, name: 'PostRank Bot' },
  { id: 35, name: 'Kosmix Voyager' },
  { id: 36, name: 'mxbot' },
  { id: 37, name: 'Knowmore Bot' },
  { id: 38, name: 'OneRiot Bot' },
  { id: 39, name: 'Morfeus Scanner' },
  { id: 40, name: 'Netcraft Survey Bot' },
  { id: 41, name: 'libwww-perl' },
  { id: 42, name: 'Comodo Certificates Spider' },
  { id: 43, name: 'Jayde Crawler' },
  { id: 44, name: 'Qualys Scanner' },
  { id: 45, name: 'SeaMonkey' },
  { id: 46, name: 'MSN/Bing Bot' },
  { id: 47, name: 'cURL' },
  { id: 48, name: 'XML Sitemaps Generator' },
  { id: 49, name: 'Python urllib' },
  { id: 50, name: 'BrowseX' },
  { id: 51, name: 'Twiceler' },
  { id: 52, name: 'ChromePlus' },
  { id: 53, name: 'SRWare Iron' },
  { id: 54, name: 'Avant' },
  { id: 55, name: 'Flock' },
  { id: 56, name: 'Opera Turbo' },
  { id: 57, name: 'CatchBot' },
  { id: 58, name: 'Pingdom Bot' },
  { id: 59, name: 'Dotcom Bot' },
  { id: 60, name: 'Montastic Bot' },
  { id: 61, name: 'Google Feedfetcher' },
  { id: 62, name: 'Yandex Bot' },
  { id: 63, name: 'Stack Rambler' },
  { id: 64, name: 'Panscient Bot' },
  { id: 65, name: 'FindLinks' },
  { id: 66, name: 'Babel Server' },
  { id: 67, name: 'Babel Distort' },
  { id: 68, name: 'Google AdsBot' },
  { id: 69, name: 'Speedy Spider' },
  { id: 70, name: 'ExaBot' },
  { id: 71, name: 'Voila Bot' },
  { id: 72, name: 'Gigabot' },
  { id: 73, name: 'Flight Deck Bot' },
  { id: 74, name: 'Nokia S60' },
  { id: 75, name: 'MJ12 Bot' },
  { id: 76, name: 'PHP' },
  { id: 77, name: 'Java' },
  { id: 78, name: 'MSIE Crawler' },
  { id: 79, name: 'HTMLParser' },
  { id: 80, name: 'Kisiwa VSE' },
  { id: 81, name: 'Alexabot' },
  { id: 82, name: 'ICC-Crawler' },
  { id: 83, name: 'GeoHasher' },
  { id: 84, name: 'obot' },
  { id: 85, name: 'YaCy-Bot' },
  { id: 86, name: 'YaCy Proxy' },
  { id: 87, name: 'DotBot' },
  { id: 88, name: 'Prism' },
  { id: 89, name: 'Websense Crawler' },
  { id: 90, name: 'picmole' },
  { id: 91, name: '.NET WebClient' },
  { id: 92, name: 'Daum Bot' },
  { id: 93, name: 'Website Optimization Analyzer' },
  { id: 94, name: 'SpamBot' },
  { id: 95, name: 'Lightspeed Crawler' },
  { id: 96, name: 'CCBot' },
  { id: 97, name: 'Larbin' },
  { id: 98, name: 'drone' },
  { id: 99, name: 'DTS Agent' },
  { id: 100, name: 'Google Toolbar' },
  { id: 101, name: 'DNS Digger Explorer' },
  { id: 102, name: 'CFNetwork' },
  { id: 104, name: 'WordPress' },
  { id: 105, name: 'Opera Mini' },
  { id: 106, name: 'Ask Crawler' },
  { id: 107, name: 'Trend Micro Crawler' },
  { id: 108, name: 'Jakarta Commons HttpClient' },
  { id: 109, name: 'Incutio XML-RPC PHP' },
  { id: 110, name: 'L.webis' },
  { id: 111, name: 'Rome Client' },
  { id: 112, name: 'Google Bot Impersonator' },
  { id: 113, name: 'SpamBot' },
  { id: 114, name: 'TalkTalk Bot' },
  { id: 115, name: 'Microsoft Office Import' },
  { id: 116, name: 'Netnir Rank Check' },
  { id: 117, name: 'Microsoft WebDAV MiniRedir' },
  { id: 118, name: 'Aria eQualizer' },
  { id: 119, name: 'Yeti (Naver Bot)' },
  { id: 120, name: 'Mail.Ru Bot' },
  { id: 121, name: 'Anonymouse' },
  { id: 122, name: 'Web Link Validator' },
  { id: 123, name: 'Nutch Based Crawler' },
  { id: 124, name: "Xenu's Link Sleuth" },
  { id: 125, name: 'MLBot' },
  { id: 126, name: 'spbot' },
  { id: 127, name: 'WebMoney Advisor Bot' },
  { id: 128, name: 'BlackBerry Internet Browser' },
  { id: 129, name: 'OSSProxy' },
  { id: 130, name: 'python-requests' },
  { id: 131, name: 'lwp-request' },
  { id: 132, name: 'Android Browser' },
  { id: 133, name: 'Lynx' },
  { id: 134, name: 'RuleSpace Bot' },
  { id: 135, name: 'Corbina Bot' },
  { id: 136, name: 'AgHaven Bot' },
  { id: 137, name: 'Digsby Favicon Fetcher' },
  { id: 138, name: 'Dom2Dom' },
  { id: 139, name: 'Seexie Bot' },
  { id: 140, name: 'Setoozbot' },
  { id: 141, name: 'Botnet Agent 141' },
  { id: 142, name: 'ia_archiver' },
  { id: 143, name: 'Chinese Bot' },
  { id: 144, name: 'PickUpJob Bot' },
  { id: 145, name: 'Blue Coat Gateway' },
  { id: 146, name: 'NetApp NetCache' },
  { id: 147, name: 'Latvian Comment Spammer' },
  { id: 149, name: 'Labhoo Bot' },
  { id: 150, name: 'Makam Bot' },
  { id: 151, name: 'Linkspimp' },
  { id: 152, name: 'BuiltWith Bot' },
  { id: 153, name: 'Blekko ScoutJet' },
  { id: 154, name: 'IBM SAI Crawler' },
  { id: 155, name: 'Scooper Bot' },
  { id: 156, name: 'Windows Media Player' },
  { id: 157, name: 'OmgiliBot' },
  { id: 158, name: 'Microsoft Internet Transfer Control' },
  { id: 159, name: 'Bixo Labs Crawler' },
  { id: 160, name: 'Crawler' },
  { id: 161, name: 'Soso Spider' },
  { id: 162, name: 'Envolk Bot' },
  { id: 163, name: 'Windows RSS Platform' },
  { id: 164, name: 'Facebook Platform' },
  { id: 166, name: 'Dillo' },
  { id: 167, name: 'DuckDuckBot' },
  { id: 168, name: 'Google Wireless Transcoder' },
  { id: 169, name: 'Websense Content Gateway' },
  { id: 170, name: 'Squid' },
  { id: 171, name: 'SQL Injection Digger' },
  { id: 172, name: 'Chinese Bot' },
  { id: 173, name: 'Comment Spammer' },
  { id: 174, name: 'SQL Injection Worm' },
  { id: 176, name: 'WinHttpRequest' },
  { id: 177, name: 'Cyveillance Bot' },
  { id: 178, name: 'Comment Spammer' },
  { id: 179, name: 'Google Desktop' },
  { id: 180, name: 'Picsearch' },
  { id: 183, name: 'Comment Spammer' },
  { id: 184, name: 'hoge' },
  { id: 185, name: 'SpamBot' },
  { id: 187, name: 'PHP OpenID' },
  { id: 188, name: 'Sogou Spider' },
  { id: 189, name: '008 (80legs Crawler)' },
  { id: 190, name: 'TurnitinBot' },
  { id: 191, name: 'Null Bot' },
  { id: 192, name: 'TextDigger Bot' },
  { id: 193, name: 'IronPort' },
  { id: 194, name: 'Apache HttpClient' },
  { id: 195, name: 'Comment Spammer' },
  { id: 196, name: 'NetProxy.info' },
  { id: 197, name: 'Vulnerability Scanner' },
  { id: 198, name: 'Change Detection Bot' },
  { id: 199, name: 'Camont Spider' },
  { id: 200, name: 'LinkedIn Bot' },
  { id: 201, name: 'Snapbot' },
  { id: 203, name: 'Careerjet Bot' },
  { id: 204, name: 'FlaxCrawler' },
  { id: 205, name: 'KAIST Bot' },
  { id: 206, name: 'JomjaiBot' },
  { id: 207, name: 'Qt' },
  { id: 208, name: 'Parked Domain Ad ClickBot' },
  { id: 209, name: 'Incapsula Service' },
  { id: 210, name: 'SpokeSpider' },
  { id: 211, name: 'MSIE Content Type Checker' },
  { id: 212, name: 'Statools Bot' },
  { id: 213, name: 'my6sense Bot' },
  { id: 214, name: 'TwengaBot-Discover' },
  { id: 215, name: 'CyberPatrol Webbot' },
  { id: 216, name: 'MaMa CaSpEr' },
  { id: 217, name: 'SQL Injection Worm' },
  { id: 221, name: 'SearchDNA Bot' },
  { id: 224, name: 'RSS Feeder' },
  { id: 229, name: 'Solomono Bot' },
  { id: 230, name: 'Moreno Bot' },
  { id: 232, name: 'Comment Spammer' },
  { id: 233, name: 'Comment Spammer' },
  { id: 234, name: '@@Version SQL Injection Worm' },
  { id: 235, name: 'Jaxified RSS Feeder' },
  { id: 236, name: 'Seznam Bot' },
  { id: 237, name: 'Sygol Bot' },
  { id: 238, name: 'Sphider' },
  { id: 239, name: 'SQL Injection Worm' },
  { id: 240, name: 'Havij SQL Injection Tool' },
  { id: 241, name: 'Keywen Bot' },
  { id: 242, name: 'Playstation' },
  { id: 243, name: 'SimplePie RSS Feeder' },
  { id: 245, name: 'Swish-e' },
  { id: 246, name: 'Cligoo Robot' },
  { id: 247, name: 'MSR-ISRCCrawler' },
  { id: 248, name: 'NTT DoCoMo Mobile Phone' },
  { id: 249, name: 'Unknown' },
  { id: 250, name: 'Hailoo Bot' },
  { id: 251, name: 'Google Custom Search' },
  { id: 252, name: 'Global Report RSS Feeder' },
  { id: 253, name: 'Youdao Bot' },
  { id: 254, name: 'Organization Proxy' },
  { id: 255, name: 'IWSS' },
  { id: 256, name: 'FindFiles.net Bot' },
  { id: 257, name: 'WebSense WebDefence' },
  { id: 258, name: 'Cyberoam Security Gateway' },
  { id: 259, name: 'Masking Proxy' },
  { id: 260, name: 'Yahoo External Cache' },
  { id: 261, name: 'RFI Worm' },
  { id: 262, name: 'JSky' },
  { id: 263, name: 'BlogLines' },
  { id: 264, name: 'N-Stalker' },
  { id: 265, name: 'FeedBurner' },
  { id: 266, name: 'Conduit Toolbar' },
  { id: 267, name: 'FeedDemon' },
  { id: 268, name: 'Acunetix Web Vulnerability Scanner' },
  { id: 269, name: 'Microsoft Internet Security and Acceleration Server' },
  { id: 270, name: 'MikroTik HTTP Proxy' },
  { id: 271, name: 'Apple PubSub' },
  { id: 272, name: 'Lusca Web Proxy' },
  { id: 273, name: 'Nessus Vulnerability Scanner' },
  { id: 275, name: 'Ad ClickBot' },
  { id: 276, name: 'Paessler Monitor' },
  { id: 277, name: 'Periscope It' },
  { id: 278, name: 'PathDefender Bot (Mcafee ScanAlert)' },
  { id: 279, name: 'WebSitePulse' },
  { id: 280, name: 'UrlCheck' },
  { id: 281, name: 'SQLMap' },
  { id: 282, name: 'Netsparker' },
  { id: 283, name: 'Blue Coat Gateway Prefetcher' },
  { id: 284, name: 'Webmetrics Monitoring Service' },
  { id: 286, name: 'FlipboardProxy' },
  { id: 287, name: 'Discobot' },
  { id: 288, name: 'Covario IDS' },
  { id: 289, name: 'Mobile Safari' },
  { id: 290, name: 'Cotendo' },
  { id: 291, name: 'Unidentified Proxy' },
  { id: 292, name: 'Comment Spammer' },
  { id: 293, name: 'Yottaa' },
  { id: 294, name: 'JikeSpider' },
  { id: 295, name: 'Magpie Crawler' },
  { id: 296, name: 'Panopta' },
  { id: 297, name: 'BuyDo' },
  { id: 298, name: 'GSA Crawler' },
  { id: 300, name: 'muieblackcat' },
  { id: 301, name: 'Joomla! Worm' },
  { id: 302, name: 'Spinn3r' },
  { id: 303, name: 'Imperva MX Server' },
  { id: 304, name: 'awstats scanner' },
  { id: 305, name: 'Microsoft Web Services Client' },
  { id: 306, name: 'Lycosa' },
  { id: 307, name: 'Websiteprotection Vulnerability Scanner' },
  { id: 308, name: 'Hyperspin' },
  { id: 309, name: 'ClickTale bot' },
  { id: 310, name: 'CrystalSemanticsBot' },
  { id: 311, name: 'Pinterest Bot' },
  { id: 312, name: 'Proximic Bot' },
  { id: 313, name: 'HP WebInspect' },
  { id: 314, name: 'Google Plus Share' },
  { id: 315, name: 'HTTrack' },
  { id: 316, name: 'Microsoft Lync' },
  { id: 317, name: 'Amazon aranhabot' },
  { id: 318, name: 'elkMonitor' },
  { id: 319, name: 'Acoon Bot' },
  { id: 320, name: 'Grepnetstat' },
  { id: 321, name: 'Gnip Bot' },
  { id: 322, name: 'Radian6 Bot' },
  { id: 323, name: 'Topsy Butterfly' },
  { id: 324, name: 'tra.cx.pider' },
  { id: 326, name: 'Android Dalvik VM' },
  { id: 328, name: 'kSOAP' },
  { id: 329, name: 'Microsoft ATL SOAP requests' },
  { id: 330, name: 'InternetVista Site Monitor' },
  { id: 331, name: 'Aihit bot' },
  { id: 332, name: 'NetSeer Crawler' },
  { id: 333, name: 'EvriNid bot' },
  { id: 334, name: 'InfoSeek SideWinder' },
  { id: 335, name: 'Updowner bot' },
  { id: 336, name: 'OpenIndex Bot' },
  { id: 337, name: 'Sucuri Bot' },
  { id: 338, name: 'Microsoft Windows Network Diagnostics Bot' },
  { id: 339, name: 'Whitehat Vulnerability Scanner' },
  { id: 340, name: 'SiteLock Vulnerability Scanner' },
  { id: 341, name: 'IBM AppScan' },
  { id: 342, name: 'HuaweiSymantecSpider' },
  { id: 343, name: 'CareerBot' },
  { id: 344, name: 'Microsoft Adidxbot' },
  { id: 345, name: 'Yahoo Pipes' },
  { id: 346, name: 'Project Wonderful Ad/Compliancy Bot' },
  { id: 347, name: 'AhrefsBot' },
  { id: 348, name: 'Google Partner Monitor' },
  { id: 349, name: 'Grapeshot Bot' },
  { id: 350, name: 'Pixray Seeker' },
  { id: 351, name: 'Bountii Bot' },
  { id: 352, name: 'YourCronTask' },
  { id: 353, name: 'Outbrain' },
  { id: 354, name: 'ShopWiki Bot' },
  { id: 355, name: 'Server Density' },
  { id: 356, name: 'CodeGuard Bot' },
  { id: 357, name: 'VaultPress Bot' },
  { id: 358, name: 'ExB Language Crawler' },
  { id: 359, name: 'Moreover Bot' },
  { id: 360, name: 'OviBrowser' },
  { id: 361, name: 'phpMyAdmin Scanner' },
  { id: 362, name: '200Please Bot' },
  { id: 363, name: 'WBSearchBot' },
  { id: 364, name: 'Security Metrics' },
  { id: 365, name: 'GlobalSign Domain Verification Agent' },
  { id: 366, name: 'Amazon ProductAdsBot' },
  { id: 367, name: 'Zing Botabot' },
  { id: 368, name: 'FeedWordPress' },
  { id: 369, name: 'Superfeedr Bot' },
  { id: 370, name: 'Techmixx Spider' },
  { id: 371, name: 'Yandex Browser' },
  { id: 372, name: 'Rogerbot Crawler' },
  { id: 373, name: 'Yunyun Spider' },
  { id: 374, name: 'Webkit Browser' },
  { id: 375, name: 'Worio Search' },
  { id: 376, name: 'JMonitoring' },
  { id: 377, name: 'CukBot' },
  { id: 378, name: 'Siteencyclopedia Bot' },
  { id: 379, name: 'JobRoboter Bot' },
  { id: 380, name: 'Artmixx Bot' },
  { id: 381, name: 'Thumbshots Bot' },
  { id: 382, name: 'AboutUs Bot' },
  { id: 383, name: 'CitiStreet Search' },
  { id: 384, name: 'Gravitybot' },
  { id: 385, name: 'AddLinkBuilding' },
  { id: 386, name: 'FreeWebMonitoring Bot' },
  { id: 387, name: 'SLI-systems Crawler' },
  { id: 388, name: 'Wiju Crawler' },
  { id: 389, name: 'UptimeRobot' },
  { id: 390, name: 'Jabse Search' },
  { id: 391, name: 'HTTP_Request2 Bot' },
  { id: 392, name: 'WebmasterCoffee Bot' },
  { id: 393, name: 'UltraSpider3000 SearchBot' },
  { id: 394, name: 'FriendFeedBot' },
  { id: 395, name: 'BigBozzBot' },
  { id: 396, name: 'HubSpot Crawler' },
  { id: 397, name: 'Caliperbot' },
  { id: 398, name: 'imrbot' },
  { id: 399, name: 'OpenfosBot' },
  { id: 400, name: 'iisbot' },
  { id: 401, name: 'FedcontractorBot' },
  { id: 402, name: 'DrupalBot' },
  { id: 403, name: 'Riddler Bot' },
  { id: 404, name: 'SiteExplorer Bot' },
  { id: 405, name: 'NewsGator Bot' },
  { id: 406, name: 'A6-Indexer Bot' },
  { id: 407, name: 'Affectv Bot' },
  { id: 408, name: 'Amazon CloudFront Client' },
  { id: 409, name: 'SnapSitemap' },
  { id: 410, name: 'Keynote' },
  { id: 411, name: 'Ezooms' },
  { id: 412, name: 'ApacheBench' },
  { id: 413, name: 'Feedly' },
  { id: 414, name: 'Internet Explorer Mobile' },
  { id: 415, name: 'Rackspace Monitoring Agent' },
  { id: 417, name: 'PhantomJS' },
  { id: 418, name: 'Google Webmasters Tools Agent' },
  { id: 420, name: 'W3C - Feed Validation' },
  { id: 421, name: 'W3C - CSS Validator' },
  { id: 422, name: 'W3C - Link checker' },
  { id: 423, name: 'W3C - Mobile OK Checker' },
  { id: 424, name: 'W3C - Unicorn Unified Validator' },
  { id: 425, name: 'W3C - Markup Validator' },
  { id: 426, name: 'W3C - Nu Markup Validation Service' },
  { id: 427, name: 'W3C - Internationalization Checker' },
  { id: 428, name: 'Browser' },
  { id: 429, name: 'Firefox (NC)' },
  { id: 430, name: 'Internet Explorer (NC)' },
  { id: 431, name: 'Chrome (NC)' },
  { id: 432, name: 'Safari (NC)' },
  { id: 433, name: 'Ararat Synapse' },
  { id: 434, name: 'SiteTruth' },
  { id: 435, name: 'Picasa Web Albums Bot' },
  { id: 436, name: 'SEMrushBot' },
  { id: 437, name: 'Easou Spider' },
  { id: 438, name: 'CheckParams' },
  { id: 439, name: 'goo' },
  { id: 440, name: 'Flipboard Mobile Client' },
  { id: 441, name: 'Nessus Cloud' },
  { id: 442, name: 'Chinese Vulnerability Scanner' },
  { id: 443, name: 'Playstation Browser' },
  { id: 445, name: 'Adbeat' },
  { id: 446, name: 'AlertSite Scan Service' },
  { id: 447, name: '6Scan Scan Service' },
  { id: 448, name: 'Beyond Security Scan Service' },
  { id: 449, name: 'Symantec Vulnerability Assessment Service' },
  { id: 450, name: 'Unknown Tor-based bot' },
  { id: 451, name: 'Malicious Tor Client' },
  { id: 452, name: 'seomatik.pl' },
  { id: 453, name: 'Google Proxy' },
  { id: 454, name: 'Linkdex' },
  { id: 455, name: 'VocusBot' },
  { id: 456, name: 'IstellaBot' },
  { id: 457, name: 'meanpath' },
  { id: 458, name: 'SiteMonitor' },
  { id: 459, name: 'FeedBooster' },
  { id: 460, name: 'Aol Reader' },
  { id: 461, name: 'feedzirra' },
  { id: 463, name: 'Arachni' },
  { id: 464, name: 'Embedly' },
  { id: 465, name: 'Coc Coc' },
  { id: 466, name: 'XBMC' },
  { id: 467, name: 'SEO Gears DIY' },
  { id: 468, name: 'UCBrowser' },
  { id: 469, name: 'IceRocket' },
  { id: 471, name: 'UniversalFeedParser' },
  { id: 472, name: 'Tweeted Times' },
  { id: 473, name: 'Ning' },
  { id: 474, name: 'Scrapy' },
  { id: 475, name: 'Silk' },
  { id: 476, name: 'Cutwail 1' },
  { id: 477, name: 'HOIC' },
  { id: 478, name: 'CA Nimsoft Monitor' },
  { id: 479, name: 'SlowLoris' },
  { id: 480, name: 'XChange' },
  { id: 481, name: 'AutoComplete+ for Magento' },
  { id: 482, name: 'Mobile Chrome' },
  { id: 483, name: 'Google Search App' },
  { id: 484, name: 'ADmantX' },
  { id: 485, name: '360Spider' },
  { id: 486, name: 'PayPal IPN' },
  { id: 487, name: 'New Relic' },
  { id: 488, name: '2Checkout' },
  { id: 489, name: 'Qt Bitcoin Trader' },
  { id: 490, name: 'Bitcoin Widget' },
  { id: 491, name: 'Gomez Agent' },
  { id: 492, name: 'Windows Phone SDK WebClient' },
  { id: 493, name: 'Cutwail 2' },
  { id: 494, name: 'MSG' },
  { id: 495, name: 'Nitol' },
  { id: 496, name: 'Koogle' },
  { id: 497, name: 'Rhino' },
  { id: 498, name: 'Cyclone' },
  { id: 499, name: 'TheGarden' },
  { id: 500, name: 'ChinaZ' },
  { id: 501, name: 'PCRat' },
  { id: 502, name: 'Gyoarazujo' },
  { id: 503, name: 'Sentry MBA' },
  { id: 504, name: 'ARME Attack' },
  { id: 505, name: 'Nitol / Rincux' },
  { id: 506, name: 'Nitol / Reconyc' },
  { id: 507, name: 'MozMSH' },
  { id: 508, name: 'PiplBot' },
  { id: 510, name: 'Authorize.net' },
  { id: 511, name: 'Bitcoin Checker' },
  { id: 512, name: 'DirtJumper' },
  { id: 513, name: 'HAX' },
  { id: 514, name: 'CopperEgg' },
  { id: 515, name: 'YisouSpider' },
  { id: 516, name: 'WordPress Brute Forcer' },
  { id: 517, name: 'Androm' },
  { id: 518, name: 'EXALEAD CloudView' },
  { id: 519, name: 'PageFreezer' },
  { id: 520, name: 'CommentLuv' },
  { id: 521, name: 'LoadImpact' },
  { id: 522, name: 'Haasonline Trade Server' },
  { id: 523, name: 'WhiteHat Aviator' },
  { id: 524, name: 'OWASP DirBuster' },
  { id: 525, name: 'CheckHost' },
  { id: 526, name: 'Blitz' },
  { id: 527, name: 'Repost' },
  { id: 528, name: 'Disqus' },
  { id: 529, name: 'AddThis' },
  { id: 530, name: 'ActiveSG' },
  { id: 531, name: 'ShipStation' },
  { id: 532, name: 'Site24x7 Tools' },
  { id: 533, name: "Tor's Hammer" },
  { id: 534, name: 'FE Client' },
  { id: 535, name: 'HULK' },
  { id: 536, name: 'Referrer SpamBot' },
  { id: 537, name: 'Qualys SSL Labs' },
  { id: 538, name: 'Shopping.com Bot' },
  { id: 539, name: 'MaxPatrol Scanner' },
  { id: 540, name: 'BOT/0.1 (BOT for JCE)' },
  { id: 541, name: 'Luna' },
  { id: 542, name: 'G-Bot' },
  { id: 543, name: 'Zscaler' },
  { id: 544, name: 'Sitebeam Bot' },
  { id: 545, name: 'JetPack' },
  { id: 546, name: 'Baidu Translate' },
  { id: 547, name: 'ICS' },
  { id: 548, name: 'MixRankBot' },
  { id: 549, name: 'CN Bot' },
  { id: 550, name: 'Skys Bot' },
  { id: 551, name: 'SmartTV' },
  { id: 552, name: 'eHarmony iOS Client' },
  { id: 553, name: 'Bitrix Bot' },
  { id: 554, name: 'vk.com Bot' },
  { id: 555, name: 'Joomla!' },
  { id: 556, name: 'GHP' },
  { id: 557, name: 'Cliqzbot' },
  { id: 558, name: 'Crowsnest' },
  { id: 559, name: '360webscan' },
  { id: 560, name: 'BLEXBot Crawler' },
  { id: 561, name: 'XoviBot' },
  { id: 562, name: 'FlamingoSearchEngine' },
  { id: 563, name: 'LinkPad Bot' },
  { id: 564, name: 'nlcrawler' },
  { id: 565, name: 'SMTbot' },
  { id: 566, name: 'Slackbot' },
  { id: 567, name: 'GoogleProducer' },
  { id: 568, name: 'Prerender' },
  { id: 569, name: 'OmniExplorer' },
  { id: 570, name: 'App.net' },
  { id: 571, name: 'DDoS Bot 571' },
  { id: 572, name: 'SputnikBot' },
  { id: 573, name: 'SuperFish' },
  { id: 574, name: 'BinaryCanary' },
  { id: 575, name: 'DomainAppender' },
  { id: 576, name: 'LeikiBot' },
  { id: 577, name: 'DiffBot' },
  { id: 578, name: 'OpenLinkProfiler' },
  { id: 579, name: 'Opera Feedfetcher' },
  { id: 580, name: 'SQLi Dumper' },
  { id: 581, name: 'gimmeBot' },
  { id: 582, name: 'AdsafeMedia' },
  { id: 583, name: 'Megaindex Link Analyzer' },
  { id: 584, name: 'TrovitBot' },
  { id: 585, name: 'Wotbox' },
  { id: 586, name: 'Veracode DAST' },
  { id: 587, name: 'feedjira' },
  { id: 588, name: 'Genieo' },
  { id: 589, name: 'Go HTTP library' },
  { id: 591, name: 'SEOstats Library' },
  { id: 592, name: 'HaleBot' },
  { id: 593, name: 'Amazon Route 53 Health Check' },
  { id: 594, name: 'webOS Browser' },
  { id: 595, name: 'Nagios Monitoring Service' },
  { id: 596, name: 'WeSEE Bot' },
  { id: 597, name: 'BetGenius Bot' },
  { id: 598, name: 'Python-httplib2' },
  { id: 599, name: 'Nintendo Browser' },
  { id: 600, name: 'THC Hydra' },
  { id: 601, name: 'LTX71' },
  { id: 602, name: 'okHTTP' },
  { id: 604, name: 'PHP Backdoor Bot' },
  { id: 605, name: 'Owlin Bot' },
  { id: 606, name: 'Sphereup Bot' },
  { id: 607, name: 'Findxbot' },
  { id: 608, name: 'Drakma - Lisp HTTP client' },
  { id: 609, name: 'Curious George' },
  { id: 610, name: 'UptimeTracker' },
  { id: 611, name: 'Cryptowatch-Observer' },
  { id: 612, name: 'Boardreader' },
  { id: 613, name: 'FatBot' },
  { id: 614, name: 'Trendiction-Bot' },
  { id: 615, name: 'Sistrix crawler' },
  { id: 616, name: 'Known Vulnerability Scanner' },
  { id: 617, name: 'Apple Bot' },
  { id: 618, name: 'DEEPCRAWL Bot' },
  { id: 619, name: 'SpotXchange Bot' },
  { id: 620, name: 'Family Tree Builder' },
  { id: 621, name: 'Chef Client' },
  { id: 622, name: 'Veooz Crawler' },
  { id: 623, name: 'HyperCrawl' },
  { id: 624, name: 'MagpieRSS' },
  { id: 625, name: 'Wget BusyBox' },
  { id: 626, name: 'Browser Impersonator' },
  { id: 627, name: 'Epiphany Browser' },
  { id: 628, name: 'Trustwave Scanner' },
  { id: 629, name: 'UnityPlayer' },
  { id: 630, name: 'MegaIndex Crawler' },
  { id: 631, name: 'Domain Re-Animator Bot' },
  { id: 632, name: 'SetCronJob Bot' },
  { id: 633, name: 'Mail.ru Chrome Bot' },
  { id: 634, name: 'Begun Bot' },
  { id: 635, name: 'MrBlack' },
  { id: 636, name: 'DDoS Bot 636' },
  { id: 637, name: 'Hackeroo' },
  { id: 638, name: 'ThousandEyes Bot' },
  { id: 639, name: 'MeWeBot' },
  { id: 640, name: 'Augure Bot' },
  { id: 641, name: 'Screaming Frog SEO Spider' },
  { id: 642, name: 'PHP DDoS Tool' },
  { id: 643, name: 'DDoS Bot 643' },
  { id: 644, name: 'CloudServerMarketSpider' },
  { id: 645, name: 'OpenHoseBot' },
  { id: 646, name: 'GroupHigh Bot' },
  { id: 647, name: 'simplereach' },
  { id: 648, name: 'DDoS Bot 648' },
  { id: 649, name: 'ControlScan Scanner' },
  { id: 650, name: 'Comodo Hacker Guardian Service' },
  { id: 651, name: 'Microsoft Edge' },
  { id: 652, name: 'PageSpeedGrader' },
  { id: 653, name: 'Qwant Bot' },
  { id: 654, name: 'Nitol B' },
  { id: 655, name: 'Joe Dog Siege' },
  { id: 656, name: 'Swiftbot' },
  { id: 657, name: 'GTmetrix' },
  { id: 658, name: 'Referrer SpamBot 2' },
  { id: 659, name: 'SaleForce Apex Web Services' },
  { id: 660, name: 'dlvr.it' },
  { id: 661, name: 'Testomatobot' },
  { id: 662, name: 'Chef Knife Opscode' },
  { id: 663, name: 'SiteLock WAF Connector' },
  { id: 664, name: 'DomainSigma' },
  { id: 665, name: 'OwnCloud News' },
  { id: 666, name: 'tweetedtimes' },
  { id: 667, name: 'Page2RSS' },
  { id: 668, name: 'Zemanta Aggregator' },
  { id: 669, name: 'Trackuity' },
  { id: 670, name: 'LinkapediaBot' },
  { id: 671, name: 'BitlyBot' },
  { id: 672, name: 'MojeekBot' },
  { id: 673, name: 'Gluten Free Crawler' },
  { id: 674, name: 'PRTGCloudBot' },
  { id: 675, name: 'Spundge' },
  { id: 677, name: 'Zabbix Web Monitor' },
  { id: 678, name: 'Microsoft Office Outlook' },
  { id: 679, name: 'GoARM / Ramgo' },
  { id: 680, name: 'CF Bypass' },
  { id: 681, name: 'SEOkicks' },
  { id: 682, name: 'TxOddsRobot' },
  { id: 684, name: 'DeuSu' },
  { id: 685, name: 'BnF Bot' },
  { id: 686, name: 'Parsijoo' },
  { id: 687, name: 'NTENTbot' },
  { id: 688, name: 'TrackIFBot' },
  { id: 689, name: 'NewsleBot' },
  { id: 690, name: 'MUSObot' },
  { id: 691, name: 'seo4ajax' },
  { id: 692, name: 'Kodi' },
  { id: 694, name: 'UniLeipzigASV' },
  { id: 695, name: 'NLB Archive Bot' },
  { id: 696, name: 'parsely' },
  { id: 697, name: 'Lipperhey' },
  { id: 698, name: 'SurdotlyBot' },
  { id: 699, name: 'Yourls' },
  { id: 700, name: 'New Zealand Library' },
  { id: 701, name: 'British Library Crawler' },
  { id: 702, name: 'BazQux' },
  { id: 703, name: 'BuzzSumo' },
  { id: 704, name: 'CocCoc Browser' },
  { id: 705, name: 'WebCEO' },
  { id: 706, name: 'EtaoSpider' },
  { id: 707, name: 'Tiny Tiny RSS' },
  { id: 708, name: 'Searchmetrics Bot' },
  { id: 709, name: 'PaperLiBot' },
  { id: 710, name: 'NewsBlur' },
  { id: 711, name: 'EveryoneSocial Bot' },
  { id: 712, name: 'Livelap Bot' },
  { id: 713, name: 'Yahoo! JAPAN' },
  { id: 714, name: 'Chartbeat uptime monitor' },
  { id: 715, name: 'Moneybookers Payment Agent' },
  { id: 716, name: 'Shellshock Vulnerability Scanner' },
  { id: 717, name: 'Joomla Vulnerability Scanner' },
  { id: 718, name: 'Siteimprove' },
  { id: 719, name: 'DDoS Bot 719' },
  { id: 720, name: 'Yandex TAPOC' },
  { id: 721, name: 'Indeed' },
  { id: 722, name: 'Linkfluence Bot' },
  { id: 723, name: 'LOVOO Client' },
  { id: 724, name: 'Fever' },
  { id: 725, name: 'Integralads Crawler' },
  { id: 726, name: 'Google Docs' },
  { id: 727, name: 'Yahoo Ad Monitoring' },
  { id: 728, name: 'Yahoo Link Preview' },
  { id: 729, name: 'Typhoeus' },
  { id: 730, name: 'WiseGuys Crawler' },
  { id: 731, name: 'Google Apps Viewer' },
  { id: 732, name: 'Avira SafeSearch' },
  { id: 733, name: 'Bloglovin' },
  { id: 734, name: 'Weebly' },
  { id: 736, name: 'Chilkat' },
  { id: 737, name: 'Puffin Browser' },
  { id: 738, name: 'SecurityHeaders.io' },
  { id: 739, name: 'Brave' },
  { id: 740, name: 'QQBrowser' },
  { id: 741, name: 'Spotify' },
  { id: 742, name: 'Rigor' },
  { id: 743, name: 'AOL Desktop' },
  { id: 744, name: 'Catchpoint' },
  { id: 745, name: 'Uptimebot' },
  { id: 747, name: 'Ruby HTTP library' },
  { id: 748, name: 'Social News Desk' },
  { id: 749, name: 'BlueSnap' },
  { id: 750, name: 'AppSpider' },
  { id: 751, name: 'Mechanize' },
  { id: 752, name: 'Raintank Collector' },
  { id: 753, name: 'Sogou Browser' },
  { id: 754, name: 'Mac Calendar Agent' },
  { id: 755, name: 'Awesomium' },
  { id: 756, name: 'DistributorDataSolutions Spider' },
  { id: 757, name: 'StackDriver' },
  { id: 758, name: 'skimbot' },
  { id: 759, name: 'Netvibes' },
  { id: 760, name: 'Comic Rocket' },
  { id: 761, name: 'Facebook Mobile App' },
  { id: 762, name: 'WhatsApp Mobile App' },
  { id: 763, name: 'IYstudio' },
  { id: 764, name: 'Zapier' },
  { id: 765, name: 'SWCD' },
  { id: 766, name: 'MetaComment' },
  { id: 767, name: 'MuckRack' },
  { id: 768, name: 'Appcelerator Titanium' },
  { id: 769, name: 'Goad' },
  { id: 771, name: 'PrintFriendly' },
  { id: 772, name: 'Weborama' },
  { id: 773, name: 'LuaSocket' },
  { id: 774, name: 'Pcore-HTTP' },
  { id: 775, name: 'AdobeAIR' },
  { id: 776, name: 'T-mobile client' },
  { id: 777, name: 'Samsung Browser' },
  { id: 778, name: 'InternetMemory crawler' },
  { id: 779, name: 'RePEc crawler' },
  { id: 780, name: 'Grabber' },
  { id: 781, name: 'Transparent health checker' },
  { id: 783, name: 'StatusCake' },
  { id: 784, name: 'RavenCrawler' },
  { id: 785, name: 'SkyClient' },
  { id: 786, name: 'celltrak' },
  { id: 787, name: 'Mirai' },
  { id: 788, name: 'GnowitNewsbot' },
  { id: 789, name: 'LogicMonitor' },
  { id: 790, name: 'Hardenize' },
  { id: 791, name: 'Cloudinary' },
  { id: 792, name: 'SXMLiveAudioPlayer' },
  { id: 793, name: 'OWASP ZAP' },
  { id: 794, name: 'Botify' },
  { id: 795, name: 'YouNow Client' },
  { id: 796, name: 'Cabify Client' },
  { id: 797, name: 'Medusa' },
  { id: 798, name: 'Amazon SNS Agent' },
  { id: 799, name: 'NightmareJS' },
  { id: 800, name: 'ActiveSync' },
  { id: 801, name: 'Cialis SpamBot' },
  { id: 802, name: 'SQL Injection Scanner' },
  { id: 803, name: 'Canadian Pharmacy SpamBot' },
  { id: 804, name: 'Microsoft-CryptoAPI' },
  { id: 805, name: 'Hackney' },
  { id: 806, name: 'GetIntent Crawler' },
  { id: 807, name: 'WormlyBot' },
  { id: 808, name: 'G2APAY' },
  { id: 809, name: 'Themes SpamBot' },
  { id: 810, name: 'Google WebLight' },
  { id: 811, name: 'Reverse B64 SpamBot' },
  { id: 813, name: 'P.A.S Client SpamBot' },
  { id: 814, name: "Let's Encrypt Helper Bot" },
  { id: 815, name: 'Generic Bot 815' },
  { id: 816, name: 'Mashery Proxy' },
  { id: 817, name: 'Generic Bot 817' },
  { id: 818, name: 'BUbiNG' },
  { id: 819, name: 'WordPress Bruteforcer' },
  { id: 820, name: 'SpamTorte v2' },
  { id: 821, name: 'ZumBot' },
  { id: 822, name: 'PowerShell' },
  { id: 823, name: 'Generic Bot 823' },
  { id: 824, name: 'IRESS Exchange Communications Service' },
  { id: 825, name: 'HC bot' },
  { id: 826, name: 'Konfabulator widget engine' },
  { id: 827, name: 'Headless Chrome' },
  { id: 828, name: 'Incapsula Cracker' },
  { id: 829, name: 'Auto Spider' },
  { id: 831, name: 'NeumobBot' },
  { id: 832, name: 'Struts Bot' },
  { id: 833, name: 'GeoPeeker' },
  { id: 834, name: 'Cloudflare AMP Discovery Fetcher' },
  { id: 835, name: 'Vivaldi' },
  { id: 836, name: 'WhatWeb' },
  { id: 837, name: 'SiteBulb' },
  { id: 838, name: 'BruteforceBot' },
  { id: 839, name: 'RootsMagic' },
  { id: 840, name: 'Electron' },
  { id: 841, name: 'Generic Vulnerability Tool 841' },
  { id: 842, name: 'WireX' },
  { id: 844, name: 'Splash' },
  { id: 846, name: 'Telegram' },
  { id: 847, name: 'ZmEu Vulnerability Scanner' },
  { id: 848, name: 'Jorgee Vulnerability Scanner' },
  { id: 849, name: 'Generic Bot 849' },
  { id: 850, name: 'TheOldReader' },
  { id: 851, name: 'G2Reader' },
  { id: 852, name: 'StartMe Bot' },
  { id: 853, name: 'SendGrid' },
  { id: 854, name: 'Imperva MX-Server' },
  { id: 856, name: 'Kapow Extraction Browser' },
  { id: 857, name: 'JuriScraper' },
  { id: 858, name: 'Bitvore' },
  { id: 859, name: 'Quanta-computing' },
  { id: 860, name: 'WAFNinja' },
  { id: 862, name: 'BufferBot' },
  { id: 863, name: 'SkypeForBusiness' },
  { id: 864, name: 'Tplmap' },
  { id: 865, name: 'WPScannerBot' },
  { id: 866, name: 'WPScan' },
  { id: 867, name: 'BrandVerity' },
  { id: 868, name: 'Manzama' },
  { id: 869, name: 'WordPress DoS Tool' },
  { id: 870, name: 'Jaunt' },
  { id: 871, name: 'MageReport' },
  { id: 872, name: 'Dcrawl' },
  { id: 873, name: 'Bot 873' },
  { id: 874, name: 'Wallarm Scanner' },
  { id: 875, name: 'Bot 875' },
  { id: 876, name: 'Movable Ink' },
  { id: 877, name: 'Spam 404 877' },
  { id: 878, name: 'SpamBot 878' },
  { id: 879, name: 'Microsoft Exchange Online' },
  { id: 880, name: 'DDoS Bot 880' },
  { id: 881, name: 'Akamai Image Server' },
  { id: 882, name: 'MeltwaterNews' },
  { id: 883, name: 'Digimind' },
  { id: 884, name: 'comScore Crawler' },
  { id: 885, name: 'iPhone Calendar Agent' },
  { id: 886, name: 'MauiBot' },
  { id: 887, name: 'Tableau Desktop' },
  { id: 888, name: 'python-aiohttp' },
  { id: 890, name: 'Alamofire Swift http library' },
  { id: 891, name: 'Node.js' },
  { id: 892, name: 'node-fetch' },
  { id: 893, name: 'Bot 893' },
  { id: 894, name: 'ManageWP' },
  { id: 895, name: 'Uptrends Site Monitor' },
  { id: 899, name: 'Android Download Manager' },
  { id: 900, name: 'AlexaMediaPlayer' },
  { id: 901, name: 'YahooMailProxy' },
  { id: 902, name: 'AFNetworking' },
  { id: 905, name: 'Apple Core Media' },
  { id: 906, name: 'SessionCam Tag tool' },
  { id: 908, name: 'Microsoft BITS' },
  { id: 909, name: 'Dynamic Signal' },
  { id: 910, name: 'Guzzle PHP HTTP client' },
  { id: 911, name: 'WeChat WebView' },
  { id: 912, name: 'Yelp iOS App' },
  { id: 913, name: 'Yelp Android App' },
  { id: 914, name: 'DDoS Bot 914' },
  { id: 917, name: 'Detectify Scanner' },
  { id: 919, name: 'Needle Node.js' },
  { id: 920, name: 'Amazon Echo device' },
  { id: 923, name: 'LG SmartTV' },
  { id: 924, name: 'ATO Wordpress Client' },
  { id: 927, name: 'ATO Client' },
  { id: 933, name: 'DDoS Bot 933' },
  { id: 934, name: 'RestSharp Client' },
  { id: 935, name: 'JAX-WS' },
  { id: 936, name: 'Runscope API' },
  { id: 938, name: 'Intuit Mint' },
  { id: 940, name: 'Instagram' },
  { id: 941, name: 'RyteBot' },
  { id: 942, name: 'Sonos Speaker' },
  { id: 943, name: 'Cambridge Audio' },
  { id: 944, name: 'Spiceworks Agent' },
  { id: 945, name: 'Nimbostratus' },
  { id: 946, name: 'Azure Traffic Manager Endpoint Monitor' },
  { id: 947, name: 'OpenBullet' },
  { id: 948, name: 'RedWolf' },
  { id: 949, name: 'OnCrawl' },
  { id: 950, name: 'Adyen Payment Client' },
  { id: 951, name: 'Freeu Browser' },
  { id: 952, name: 'Amigo Browser' },
  { id: 953, name: 'Azure AD' },
  { id: 954, name: 'AspiegelBot' },
  { id: 955, name: 'Datadog Synthetics' },
  { id: 956, name: 'Hookshot' },
  { id: 957, name: 'Fornova' },
  { id: 958, name: 'Apple App Site Association CDN bot' },
  { id: 959, name: 'Nightmare Stresser' },
  { id: 960, name: 'Line' },
  { id: 961, name: 'purplemet' },
  { id: 963, name: 'Expanse' },
  { id: 964, name: 'Microsoft Power BI' },
  { id: 965, name: 'Sajari' },
  { id: 966, name: 'Nuclei' },
  { id: 967, name: 'Postman' },
  { id: 968, name: 'Baqend' },
  { id: 969, name: 'Google PageSpeed' },
  { id: 971, name: 'Safe Exam Browser' },
  { id: 972, name: 'Neeva' },
  { id: 973, name: 'Stamps' },
  { id: 974, name: 'ZIQY' },
  { id: 975, name: 'Smartly.io' },
  { id: 977, name: 'Speedpay' },
  { id: 978, name: 'Nextiva' },
  { id: 979, name: 'OutSystems' },
  { id: 980, name: 'Google Wallet' },
  { id: 981, name: 'Better Uptime' },
  { id: 982, name: 'Bank Tabungan Negara (BTN)' },
  { id: 983, name: 'Dart API Library' },
  { id: 984, name: 'undici' },
  { id: 985, name: 'Outlook Anywhere - MSRPC' },
];
